### ISSUE TITLE
对签到结果是否考虑增加一下反馈

### ISSUE THREAD

**Issue by lizijing98** [sudojia/AutoTaskScript#1]
譬如网站签到成功或当日已签到的接口调用结果的反馈

**Comment by sudojia** [comment]
你是指消息推送吗，就是签到成功之后把签到结果推送到tg或者wechat？

**Comment by sudojia** [comment]
如果是我上述所说的，这已经实现了啊 [#消息推送变量（可选）](https://github.com/sudojia/scripts#%E6%B6%88%E6%81%AF%E6%8E%A8%E9%80%81%E5%8F%98%E9%87%8F%E5%8F%AF%E9%80%89)

![image](https://user-images.githubusercontent.com/86390796/153756290-9ebcd48a-f7eb-46f3-a507-89d0299f37e9.png)

**Comment by lizijing98** [comment]
抱歉，之前 tg 的 bot 没设置好，报了 500 的错误😂
