### ISSUE TITLE
雷达汽车

### ISSUE THREAD

**Issue by TeslaCybercab** [sudojia/AutoTaskScript#100]
### 📲 服务平台

客户端

### 🧸 应用官网

雷达汽车APP

### 🤔 活动入口

右下角->签到 以及中间的 积分任务

### 🎁 奖励说明

积分兑实物

### 🔗 附加信息

![3ad862b8472cbe66242870b7627965d9](https://github.com/user-attachments/assets/88221f28-70bb-4d31-b0a1-d1f4bb64a6ad)

**Comment by sudojia** [comment]
模拟器运行闪退

![image](https://github.com/user-attachments/assets/e0dbb008-c576-4c0d-8459-0de402545a07)
