### ISSUE TITLE
33台词

### ISSUE THREAD

**Issue by billowssun** [sudojia/AutoTaskScript#103]
### 📲 服务平台

网页

### 🧸 应用官网

https://33.agilestudio.cn/

### 🤔 活动入口

https://33.agilestudio.cn/my-integral

### 🎁 奖励说明

每天签到可获得5积分

### 🔗 附加信息

无

**Comment by sudojia** [comment]
https://github.com/sudojia/AutoTaskScript/blob/script/src/web/sudojia_33agilestudio.js

**Comment by billowssun** [comment]
感谢大佬
