### ISSUE TITLE
新湖南

### ISSUE THREAD

**Issue by TeslaCybercab** [sudojia/AutoTaskScript#105]
### 📲 服务平台

客户端

### 🧸 应用官网

新湖南APP

### 🤔 活动入口

我的→天天领积分

### 🎁 奖励说明

红包或实物

### 🔗 附加信息

![1](https://github.com/user-attachments/assets/89101bda-9f84-4656-aad0-fe4914e99ea4)
![2](https://github.com/user-attachments/assets/e6deae4c-b3a3-465e-bb1a-25a8adf678ae)

**Comment by sudojia** [comment]
刚注册就黑号了

![image](https://github.com/user-attachments/assets/f83ef917-5670-4327-8600-78ff35130c8d)

**Comment by TeslaCybercab** [comment]
@sudojia 用手机注册又正常了

**Comment by sudojia** [comment]
> @sudojia 用手机注册又正常了

就是手机号注册的

**Comment by sudojia** [comment]
> @sudojia 用手机注册又正常了

一做任务就黑号

**Comment by sudojia** [comment]
`https://github.com/sudojia/AutoTaskScript/blob/script/src/client/sudojia_xhn.js`
