### ISSUE TITLE
馬伍旺饮料厂签到异常

### ISSUE THREAD

**Issue by LiuRJ99** [sudojia/AutoTaskScript#109]
### 📜 脚本名称

task sudojia_AutoTaskScript/src/wx_mini/sudojia_mawuwang.js

### 🤔 问题描述

运行脚本时，提示成功，但是在官网上查看，已清除缓存，仍是未显示积分，最近积分日期也是昨天的
截图
![image](https://github.com/user-attachments/assets/ad314715-6449-452b-bfd9-790dc5ef06d0)

### 🔄 重现过程

1.已按照文档说明要求获取的 Cookie 格式
![image](https://github.com/user-attachments/assets/d5d5acec-c50d-4dcf-99f2-dd38a6051734)

2.重新拉取最新版脚本

3.点击运行

4.日志提示打卡成功

### 🌐 网络自检

是

## 开始执行... 2024-11-17 06:48:00

【脚本作者】sudojia
【脚本地址】https://github.com/sudojia/AutoTaskScript
【当前版本】v1.0.0
【最新版本】v1.0.0
【最近更新】2024-09-01
【更新内容】新增馬伍旺饮料厂每日签到

开始执行馬伍旺饮料厂

*****第[1]个馬伍旺饮料厂账号*****
undefined登录成功~
签到失败： 活动不在进行中
当前积分：1.8
暂无过期积分

go-cqhttp发送通知消息成功🎉

🔔馬伍旺饮料厂, 结束! 🕛 139.849 秒

## 执行结束... 2024-11-17 06:50:24  耗时 144 秒

**Comment by starsink-d** [comment]
结果无异常你是怎么说出来的?  "签到失败： 活动不在进行中" 活动都结束了啊,哪里给你积分?

**Comment by LiuRJ99** [comment]
> 结果无异常你是怎么说出来的? "签到失败： 活动不在进行中" 活动都结束了啊,哪里给你积分?

我理解这是一个签到任务，我可以手动签，是不是接口有变化导致的。

**Comment by starsink-d** [comment]
看日志啊,不是说活动结束了嘛?所以让作者换个活动id就可以了,只是id改变了

**Comment by LiuRJ99** [comment]
哦哦，感谢，其他的也遇到类似情况，这个不能提bug的吗？
那我先关掉咯。
