### ISSUE TITLE
飞蚂蚁旧衣回收-签到显示：无效授权，其他

### ISSUE THREAD

**Issue by LiuRJ99** [sudojia/AutoTaskScript#110]
### 📜 脚本名称

task sudojia_AutoTaskScript/src/wx_mini/sudojia_flyant.js

### 🤔 问题描述

运行脚本时，兑换步数正常，签到失败：无效授权。
![image](https://github.com/user-attachments/assets/ffeecb5d-dc08-42c4-b309-397f28b3321c)

### 🔄 重现过程

1. 已按照文档说明要求获取的 Cookie 格式
![image](https://github.com/user-attachments/assets/e7911511-1370-48c3-b048-0265baa3a55c)
3. 重新拉取最新版脚本
4. 点击运行
5. 日志提示打卡成功

### 🌐 网络自检

是

### 🔗 附加信息

【脚本作者】sudojia
【脚本地址】https://github.com/sudojia/AutoTaskScript
【当前版本】v1.0.1
【最新版本】v1.0.1
【最近更新】2024-10-09
【更新内容】调用顺序更改

开始执行飞蚂蚁旧衣回收

已随机分配 User-Agent

Mozilla/5.0 (Linux; Android 14; 23013RK75C Build/UKQ1.230804.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/116.0.0.0 Mobile Safari/537.36 XWEB/1160083 MMWEBSDK/20240301 MMWEBID/5940 MicroMessenger/8.0.48.2580(0x28003096) WeChat/arm64 Weixin NetType/5G Language/zh_CN ABI/arm64

*****第[1]个飞蚂蚁旧衣回收账号*****
早起打卡成功：操作成功
**签到失败：无效授权**
已连续签到：1天
已获取：34环保豆
已使用：20环保豆
当前剩余：14环保豆
第1次步数兑换...
步数兑换成功！

第2次步数兑换...
步数兑换成功！

第3次步数兑换...
步数兑换成功！

抽奖成功，获得【环保豆5颗】
早起报名成功，恭喜您成功投注10颗环保豆

go-cqhttp发送通知消息成功🎉

🔔飞蚂蚁旧衣回收, 结束! 🕛 196.892 秒

**Comment by sudojia** [comment]
作者无任何问题，无法排查

![image](https://github.com/user-attachments/assets/a17d49ea-e2a9-4409-9117-2cbbc6408b98)
