### ISSUE TITLE
蜜雪冰城-签到失败

### ISSUE THREAD

**Issue by LiuRJ99** [sudojia/AutoTaskScript#112]
### 📜 脚本名称

task sudojia_AutoTaskScript/src/wx_mini/sudojia_mxbc.js

### 🤔 问题描述

已经抓取了最新的accesstoken，但日志提示invalid sign Token 失效。

### 🔄 重现过程

1. 已按照文档说明要求获取的 Cookie 格式
![image](https://github.com/user-attachments/assets/fb3f40ba-e4a1-4b53-b50e-fac4882d6cf7)
![image](https://github.com/user-attachments/assets/34ca4e23-6592-4de6-9394-92340c42ac27)

2. 重新拉取最新版脚本
3. 点击运行
4. 日志提示打卡成功

### 🌐 网络自检

是

### 🔗 附加信息

【脚本作者】sudojia
【脚本地址】https://github.com/sudojia/AutoTaskScript
【当前版本】v1.0.0
【最新版本】v1.0.0
【最近更新】2024-07-27
【更新内容】新增蜜雪冰城每日签到！

开始执行蜜雪冰城

已随机分配 User-Agent

Mozilla/5.0 (Linux; Android 14; PJD110 Build/UKQ1.230924.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/116.0.0.0 Mobile Safari/537.36 XWEB/1160117 MMWEBSDK/20240404 MMWEBID/1658 MicroMessenger/8.0.49.2600(0x28003137) WeChat/arm64 Weixin NetType/5G Language/zh_CN ABI/arm64

*****第[1]个蜜雪冰城账号*****
invalid sign
Token 失效

go-cqhttp发送通知消息成功🎉

🔔蜜雪冰城, 结束! 🕛 113.399 秒

**Comment by hhtnFxQVwQntBLkULKjy** [comment]
一样的问题

**Comment by sudojia** [comment]
重新拉取脚本
