### ISSUE TITLE
吉利银河

### ISSUE THREAD

**Issue by QQ313691952** [sudojia/AutoTaskScript#114]
### 📲 服务平台

客户端

### 🧸 应用官网

吉利银河app

### 🤔 活动入口

每日签到

### 🎁 奖励说明

签到积分兑换

### 🔗 附加信息

![微信图片_20241127103106](https://github.com/user-attachments/assets/6ef3177c-f61a-4445-bbc5-7310f16168e1)
![微信图片_20241127103108](https://github.com/user-attachments/assets/f11470ca-8c14-4704-b5ec-54e5894fd648)
![微信图片_20241127103111](https://github.com/user-attachments/assets/3401bdea-8a17-48e4-9060-c8004ab28a4a)

**Comment by sudojia** [comment]
这个 issues 前面有人提过，我模拟器闪退，写不了
