### ISSUE TITLE
塔斯丁中国汉堡

### ISSUE THREAD

**Issue by starsink-d** [sudojia/AutoTaskScript#118]
### 📲 服务平台

微信小程序

### 🧸 应用官网

入口:#小程序://塔斯汀+/TnY2wQzB1Jp0nYB

### 🤔 活动入口

底部积分商城->右上角每日签到

### 🎁 奖励说明

签到领免费实物,然后积分可以抢购汉堡之类的

### 🔗 附加信息

![image](https://github.com/user-attachments/assets/963b120e-b5ac-4b2f-b4cf-5794c4759505)
![image](https://github.com/user-attachments/assets/67b10996-4d06-498a-89e4-db4f2ef46af1)

**Comment by sudojia** [comment]
https://github.com/sudojia/AutoTaskScript/blob/script/src/wx_mini/sudojia_tastientech.js
