### ISSUE TITLE
顾家家居Parametersign参数缺失

### ISSUE THREAD

**Issue by TeslaCybercab** [sudojia/AutoTaskScript#120]
### 📜 脚本名称

顾家家居

### 🤔 问题描述

顾家家居Parametersign参数缺失

### 🔄 重现过程

无

### 🌐 网络自检

是

### 🔗 附加信息

请求 https://mc.kukahome.com/club-server/applet/waterfall/newWaterfall 失败: 请求头[Parametersign]参数缺失
获取文章时发生异常：Error: 请求头[Parametersign]参数缺失

**Comment by sudojia** [comment]
沙雕没事做，多加了个参数签名，有空再说吧

![image](https://github.com/user-attachments/assets/30730c61-d3be-4f13-bb8c-8bcce66da626)

**Comment by sudojia** [comment]
已解决，重新拉新脚本
