### ISSUE TITLE
图虫

### ISSUE THREAD

**Issue by TeslaCybercab** [sudojia/AutoTaskScript#123]
### 📜 脚本名称

tuchong.js

### 🤔 问题描述

账号密码都没错，也在APP用密码登录试过正常没事，但脚本显示账号密码错误

### 🔄 重现过程

无

### 🌐 网络自检

否

### 🔗 附加信息

![image](https://github.com/user-attachments/assets/894cc722-1311-4336-a36d-91a037bccd71)

**Comment by sudojia** [comment]
你是ios吗

**Comment by sudojia** [comment]
重新再试试，不行我也没辙

**Comment by TeslaCybercab** [comment]
@sudojia 更新完 就可以了
