### ISSUE TITLE
兴攀农场

### ISSUE THREAD

**Issue by TeslaCybercab** [sudojia/AutoTaskScript#124]
### 📜 脚本名称

xpfarm.js

### 🤔 问题描述

重新抓Authorization也显示过期

### 🔄 重现过程

无

### 🌐 网络自检

否

### 🔗 附加信息

![image](https://github.com/user-attachments/assets/133f71c5-43f0-4123-9e92-f96655b391a6)

**Comment by sudojia** [comment]
这个放弃吧，不打算维护了，因为跑几年都不一定能兑换到
