### ISSUE TITLE
阿里云签到失效了

### ISSUE THREAD

**Issue by veip007** [sudojia/AutoTaskScript#13]
阿里账号【1】请求接口异常, 可能是 refresh_token 失效了, 请重新获取 

获取了几次都是这个提示
另外请问阿里云多账号是否是这样的格式：
eg:72924e9XXXXXXXXXX&eg:aec285eff7XXXXXX&eg:aec2185eff7XXXXXX

**Comment by sudojia** [comment]
格式是 72924e9XXXXXXXXXX&aec285eff7XXXXXX&aec2185eff7XXXXXX
不要带eg，eg是示例的意思，不过现在阿里云盘我刚刚抓包发现请求头多了签名验证的参数，估计也不行了，这个签名参数不知道是在哪里获取的，本人能力有限，后续看看有没有大佬解解吧
