### ISSUE TITLE
阿里云盘签到失败，提示：阿里账号【1】请求接口异常, 可能是 refresh_token 失效了, 请重新获取 refresh_token 

### ISSUE THREAD

**Issue by uuuuuundefined** [sudojia/AutoTaskScript#14]
报错提示：“阿里账号【1】请求接口异常, 可能是 refresh_token 失效了, 请重新获取 refresh_token ”

确定获取的最新且可用的refresh_token ，而且 为了获取最新的refresh_token ，重复登录了几次。

![1716541201855](https://github.com/sudojia/scripts/assets/39209399/4f5a7406-9462-4d31-8640-4d22b32791f1)

**Comment by sudojia** [comment]
因为获取奖励的接口请求头添加了签名算法，所以在请求失败的时候加了这句话，现在移除了获取奖励接口，仅支持签到了，没办法，能力有限
