### ISSUE TITLE
库街区显示token失效

### ISSUE THREAD

**Issue by Chilzen-smx** [sudojia/AutoTaskScript#16]

**Comment by sudojia** [comment]
1. 请确保 Token 获取的有效性[【查看库街区获取 Token 的方式】](https://github.com/sudojia/scripts/blob/script/docs/ENV_DESC.md#%E5%BA%93%E8%A1%97%E5%8C%BA)

2. 请提供日志详细信息

3. 本人刚刚已测试，并无问题，请按照上述所说的方式获取 Token 后重试！

   ![image](https://github.com/sudojia/scripts/assets/86390796/f006bf86-3926-4bef-a4bc-8166ab37299e)

**Comment by sudojia** [comment]
> _No description provided._

我大概知道了，稍等我修复一下

**Comment by sudojia** [comment]
> _No description provided._

请更新最新脚本后重试！

**Comment by Chilzen-smx** [comment]
测试已成功，谢谢
