### ISSUE TITLE
推送能否合并推送呢？

### ISSUE THREAD

**Issue by Crazybbok** [sudojia/AutoTaskScript#19]
因为执行的脚本较多，通知server酱的次数有限，想问下是否可以调整成一次性执行后推送呢

**Comment by sudojia** [comment]
暂时不会调整也没有计划调整，有其他推送服务可供选择，比如：[PushPlus](https://www.pushplus.plus/)，此外，消息推送功能虽然便利，但并非核心功能，它的存在主要是为了提供额外的便利性，而不是必需的
