### ISSUE TITLE
V2EX 账户余额单位弄错了

### ISSUE THREAD

**Issue by LisonFan** [sudojia/AutoTaskScript#20]
![image](https://github.com/sudojia/scripts/assets/9424775/e1152a5d-6302-4a27-a32f-3a10443f8bff)

金 银 铜
![image](https://github.com/sudojia/scripts/assets/9424775/e83a0b9d-618a-47c8-9ae4-84ca6e888aa8)

**Comment by sudojia** [comment]
其实这个问题我知道，因为我没有金😭

![image](https://github.com/sudojia/scripts/assets/86390796/591df81d-3f2f-4034-94f2-e92dd18e5083)

你可以 F12 选取这段元素的 html 发我，我去改改

**Comment by sudojia** [comment]
> ![image](https://private-user-images.githubusercontent.com/9424775/340883971-e1152a5d-6302-4a27-a32f-3a10443f8bff.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg4MDM1MjgsIm5iZiI6MTcxODgwMzIyOCwicGF0aCI6Ii85NDI0Nzc1LzM0MDg4Mzk3MS1lMTE1MmE1ZC02MzAyLTRhMjctYTMyZi0zYTEwNDQzZjhiZmYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYxOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MTlUMTMyMDI4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZGJmNGRmNmZjNzMyNDkyM2JjMjI3ODQ3NjdiYWVhMTA5MDAwZDBkNzBhYmEwNDc5ZTY0MTc2Zjc4YmY3OTkzOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.n3c6FB-6YQydOWoPdgFxiyizdt4qfV_nZW0mbYxQNeE)
> 
> 金 银 铜 ![image](https://private-user-images.githubusercontent.com/9424775/340883988-e83a0b9d-618a-47c8-9ae4-84ca6e888aa8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg4MDM1MjgsIm5iZiI6MTcxODgwMzIyOCwicGF0aCI6Ii85NDI0Nzc1LzM0MDg4Mzk4OC1lODNhMGI5ZC02MThhLTQ3YzgtOWFlNC04NGNhNmU4ODhhYTgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYxOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MTlUMTMyMDI4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZjkyNjM2NTdhZjQ5YmRjNTAwYzlkZmVmMzk5MWY0MWI4Y2IwMjczODI2ZjY1NzI1OTNmZDdkNDM0YzgwNWY0YSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.SgQ6x3aPMLWlSzwjOpjH3n_l8YqDp--mjFPj2df7uIM)

其实这个问题我知道，因为我没有金😭

![image](https://github.com/sudojia/scripts/assets/86390796/a5bb397d-3343-4f03-8ed6-44abb69bd51e)

你可以 F12 选取这段元素的 html 发我，我去改改

**Comment by LisonFan** [comment]
> > ![image](https://private-user-images.githubusercontent.com/9424775/340883971-e1152a5d-6302-4a27-a32f-3a10443f8bff.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg4MDM1MjgsIm5iZiI6MTcxODgwMzIyOCwicGF0aCI6Ii85NDI0Nzc1LzM0MDg4Mzk3MS1lMTE1MmE1ZC02MzAyLTRhMjctYTMyZi0zYTEwNDQzZjhiZmYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYxOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MTlUMTMyMDI4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZGJmNGRmNmZjNzMyNDkyM2JjMjI3ODQ3NjdiYWVhMTA5MDAwZDBkNzBhYmEwNDc5ZTY0MTc2Zjc4YmY3OTkzOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.n3c6FB-6YQydOWoPdgFxiyizdt4qfV_nZW0mbYxQNeE)
> > 金 银 铜 ![image](https://private-user-images.githubusercontent.com/9424775/340883988-e83a0b9d-618a-47c8-9ae4-84ca6e888aa8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg4MDM1MjgsIm5iZiI6MTcxODgwMzIyOCwicGF0aCI6Ii85NDI0Nzc1LzM0MDg4Mzk4OC1lODNhMGI5ZC02MThhLTQ3YzgtOWFlNC04NGNhNmU4ODhhYTgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYxOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MTlUMTMyMDI4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZjkyNjM2NTdhZjQ5YmRjNTAwYzlkZmVmMzk5MWY0MWI4Y2IwMjczODI2ZjY1NzI1OTNmZDdkNDM0YzgwNWY0YSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.SgQ6x3aPMLWlSzwjOpjH3n_l8YqDp--mjFPj2df7uIM)
> 
> 其实这个问题我知道，因为我没有金😭
> 
> ![image](https://private-user-images.githubusercontent.com/86390796/341090043-a5bb397d-3343-4f03-8ed6-44abb69bd51e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg4MDM3OTIsIm5iZiI6MTcxODgwMzQ5MiwicGF0aCI6Ii84NjM5MDc5Ni8zNDEwOTAwNDMtYTViYjM5N2QtMzM0My00ZjAzLThlZDYtNDRhYmI2OWJkNTFlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE5VDEzMjQ1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY1YjhmNWI0YzhhMjM3NGIzMTZkZjRjYzVjOGIwMGE1OTg0ZTE2NDJkZmQ0M2U2ZGMyNThkNzg4NjRiNzFlMDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.WvNMH6-wA-JxjFpUB73WBDrD95--rFGQtxjudZOVxos)
> 
> 你可以 F12 选取这段元素的 html 发我，我去改改

```
<div class="balance_area bigger" style="font-size: 24px; line-height: 24px;">18 <img src="/static/img/gold@2x.png" height="16" alt="G" border="0"> 24 <img src="/static/img/silver@2x.png" height="16" alt="S" border="0"> 86 <img src="/static/img/bronze@2x.png" height="16" alt="B" border="0"></div>
```

**Comment by sudojia** [comment]
> > > ![image](https://private-user-images.githubusercontent.com/9424775/340883971-e1152a5d-6302-4a27-a32f-3a10443f8bff.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg4MDM1MjgsIm5iZiI6MTcxODgwMzIyOCwicGF0aCI6Ii85NDI0Nzc1LzM0MDg4Mzk3MS1lMTE1MmE1ZC02MzAyLTRhMjctYTMyZi0zYTEwNDQzZjhiZmYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYxOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MTlUMTMyMDI4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZGJmNGRmNmZjNzMyNDkyM2JjMjI3ODQ3NjdiYWVhMTA5MDAwZDBkNzBhYmEwNDc5ZTY0MTc2Zjc4YmY3OTkzOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.n3c6FB-6YQydOWoPdgFxiyizdt4qfV_nZW0mbYxQNeE)
> > > 金 银 铜 ![image](https://private-user-images.githubusercontent.com/9424775/340883988-e83a0b9d-618a-47c8-9ae4-84ca6e888aa8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg4MDM1MjgsIm5iZiI6MTcxODgwMzIyOCwicGF0aCI6Ii85NDI0Nzc1LzM0MDg4Mzk4OC1lODNhMGI5ZC02MThhLTQ3YzgtOWFlNC04NGNhNmU4ODhhYTgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYxOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MTlUMTMyMDI4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZjkyNjM2NTdhZjQ5YmRjNTAwYzlkZmVmMzk5MWY0MWI4Y2IwMjczODI2ZjY1NzI1OTNmZDdkNDM0YzgwNWY0YSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.SgQ6x3aPMLWlSzwjOpjH3n_l8YqDp--mjFPj2df7uIM)
> > 
> > 
> > 其实这个问题我知道，因为我没有金😭
> > ![image](https://private-user-images.githubusercontent.com/86390796/341090043-a5bb397d-3343-4f03-8ed6-44abb69bd51e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg4MDM3OTIsIm5iZiI6MTcxODgwMzQ5MiwicGF0aCI6Ii84NjM5MDc5Ni8zNDEwOTAwNDMtYTViYjM5N2QtMzM0My00ZjAzLThlZDYtNDRhYmI2OWJkNTFlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE5VDEzMjQ1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY1YjhmNWI0YzhhMjM3NGIzMTZkZjRjYzVjOGIwMGE1OTg0ZTE2NDJkZmQ0M2U2ZGMyNThkNzg4NjRiNzFlMDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.WvNMH6-wA-JxjFpUB73WBDrD95--rFGQtxjudZOVxos)
> > 你可以 F12 选取这段元素的 html 发我，我去改改
> 
> ```
> <div class="balance_area bigger" style="font-size: 24px; line-height: 24px;">18 <img src="/static/img/gold@2x.png" height="16" alt="G" border="0"> 24 <img src="/static/img/silver@2x.png" height="16" alt="S" border="0"> 86 <img src="/static/img/bronze@2x.png" height="16" alt="B" border="0"></div>
> ```

应该没问题了
