### ISSUE TITLE
全棉时代抓包没有找到host

### ISSUE THREAD

**Issue by Crazybbok** [sudojia/AutoTaskScript#21]
微信小程序是全棉时代官方商城吗？抓包了几次没有文档中对应的host的信息诶

**Comment by Crazybbok** [comment]
要使用全棉时代官方自营商城 已解决

**Comment by sudojia** [comment]
> 微信小程序是全棉时代官方商城吗？抓包了几次没有文档中对应的host的信息诶

我也才发现有两个小程序，并且这俩接口都不一样，说明积分可以累加，现在写了个官方的脚本了

sudojia_all_cotton_self.js 对应的是全棉时代官方自营商城

sudojia_all_cotton_official.js 对应的是全棉时代官方商城

**Comment by Crazybbok** [comment]
> > 微信小程序是全棉时代官方商城吗？抓包了几次没有文档中对应的host的信息诶
> 
> 我也才发现有两个小程序，并且这俩接口都不一样，说明积分可以累加，现在写了个官方的脚本了
> 
> sudojia_all_cotton_self.js 对应的是全棉时代官方自营商城
> 
> sudojia_all_cotton_official.js 对应的是全棉时代官方商城

ok 但是我在全棉时代官方商城抓包抓不到 Host：mall.winnermedical.com下的字段，自营的可以抓到
