### ISSUE TITLE
贴吧签到无效，不知道哪儿出问题了

### ISSUE THREAD

**Issue by xoyo-tyu** [sudojia/AutoTaskScript#27]
开始执行贴吧签到

********第【1】个贴吧签到账号********
正在开始签到所有贴吧, 共计 5 个贴吧, 请耐心等待...
push+发送一对一通知消息完成。

实际上手机登录贴吧发现都是没有签到，不知道哪儿错了，部署在青龙面板上，贴吧cookie也是获取了BDUSS部分的。

**Comment by sudojia** [comment]
重试几次吧，我没有输出log，我也不清楚，我这里是可以的
![image](https://github.com/sudojia/scripts/assets/86390796/67cd1f49-5323-4a9f-88af-2978c76089b4)

![image](https://github.com/sudojia/scripts/assets/86390796/1d034e19-77e9-42ac-b9f3-1922f0dfe5d0)

**Comment by sudojia** [comment]
> 开始执行贴吧签到
> 
> **第【1】个贴吧签到账号** 正在开始签到所有贴吧, 共计 5 个贴吧, 请耐心等待... push+发送一对一通知消息完成。
> 
> 实际上手机登录贴吧发现都是没有签到，不知道哪儿错了，部署在青龙面板上，贴吧cookie也是获取了BDUSS部分的。

重新拉取新脚本试试吧

**Comment by xoyo-tyu** [comment]
更新了你下午改的代码，现在报的错误是这样了

**Comment by xoyo-tyu** [comment]
![err](https://github.com/sudojia/scripts/assets/55444712/dcbb17a0-4c3a-4f23-8b66-f27653880646)

**Comment by sudojia** [comment]
> ![err](https://private-user-images.githubusercontent.com/55444712/343766279-dcbb17a0-4c3a-4f23-8b66-f27653880646.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk0OTQ4MzgsIm5iZiI6MTcxOTQ5NDUzOCwicGF0aCI6Ii81NTQ0NDcxMi8zNDM3NjYyNzktZGNiYjE3YTAtNGMzYS00ZjIzLThiNjYtZjI3NjUzODgwNjQ2LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI3VDEzMjIxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBlNmFhZGJkZDIzODA1ZjZjMDYzNDVhMjZmYTU1ZDRiMmI0ZTQ4MDI1NGRkNjJjYjdkMTY3NWM1YzZhOGRjODEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.k2XZWmpdtOL5_PxnjD5ljW4avhQ2-UiGU4J5gt3gBno)

看这log，应该是请求的时候，有未转义的贴吧，导致报错了，后面的基本也是前面报错导致获取不到而报错

**Comment by sudojia** [comment]
> ![err](https://private-user-images.githubusercontent.com/55444712/343766279-dcbb17a0-4c3a-4f23-8b66-f27653880646.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk0OTQ4MzgsIm5iZiI6MTcxOTQ5NDUzOCwicGF0aCI6Ii81NTQ0NDcxMi8zNDM3NjYyNzktZGNiYjE3YTAtNGMzYS00ZjIzLThiNjYtZjI3NjUzODgwNjQ2LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI3VDEzMjIxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBlNmFhZGJkZDIzODA1ZjZjMDYzNDVhMjZmYTU1ZDRiMmI0ZTQ4MDI1NGRkNjJjYjdkMTY3NWM1YzZhOGRjODEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.k2XZWmpdtOL5_PxnjD5ljW4avhQ2-UiGU4J5gt3gBno)

你把你关注的贴吧发我瞅瞅 [@sudojia](https://t.me/sudojia)

**Comment by sudojia** [comment]
有可能是有空格的贴吧，那么还得replace  %20来转义

**Comment by xoyo-tyu** [comment]
猪鼻蛇
上海爬宠
玉米蛇
上海联通
梦想e卡

我有个账号就关注这几个吧，也是报同样的错，没有Telegram Messenger 账号

**Comment by sudojia** [comment]
> 猪鼻蛇 上海爬宠 玉米蛇 上海联通 梦想e卡
> 
> 我有个账号就关注这几个吧，也是报同样的错，没有Telegram Messenger 账号

你用GitHub Actions测试一下是否是运行环境问题，我明天再测试一下这几个贴吧

**Comment by xoyo-tyu** [comment]
刚在GitHub Actions测试了下，是可以的，然后在青龙面板上点击运行也可以了，明天看看，谢谢~

开始执行贴吧签到

********第【1】个贴吧签到账号********
正在开始签到所有贴吧, 共计 19 个贴吧, 请耐心等待...
成功签到19个, 失败0个, 过滤失效贴吧0个

********第【2】个贴吧签到账号********
正在开始签到所有贴吧, 共计 5 个贴吧, 请耐心等待...
成功签到5个, 失败0个, 过滤失效贴吧0个
push+发送一对一通知消息完成。

**Comment by sudojia** [comment]
好的

**Comment by xoyo-tyu** [comment]
GitHub Actions是可以运行的，青龙面板不行还是一样的报错。

每天只要GitHub Actions跑过一次，青龙面板再跑是不报错，青龙会显示：

开始执行贴吧签到

第【1】个贴吧签到账号
正在开始签到所有贴吧, 共计 19 个贴吧, 请耐心等待...
成功签到19个, 失败0个, 过滤失效贴吧0个

第【2】个贴吧签到账号
正在开始签到所有贴吧, 共计 5 个贴吧, 请耐心等待...
成功签到5个, 失败0个, 过滤失效贴吧0个
push+发送一对一通知消息完成。

但是每天先运行青龙面板跑签到，就会出现先前的转义错误：

********第【2】个贴吧签到账号********
请求失败： TypeError [ERR_UNESCAPED_CHARACTERS]: Request path contains unescaped characters
    at new NodeError (node:internal/errors:405:5)
    at new ClientRequest (node:_http_client:183:13)
    at Object.request (node:https:358:10)
    at RedirectableRequest._performRequest (/root/.local/share/pnpm/global/5/.pnpm/follow-redirects@1.15.3_debug@4.3.4/node_modules/follow-redirects/index.js:296:24)
    at new RedirectableRequest (/root/.local/share/pnpm/global/5/.pnpm/follow-redirects@1.15.3_debug@4.3.4/node_modules/follow-redirects/index.js:69:8)
    at Object.request (/root/.local/share/pnpm/global/5/.pnpm/follow-redirects@1.15.3_debug@4.3.4/node_modules/follow-redirects/index.js:535:14)
    at dispatchHttpRequest (/root/.local/share/pnpm/global/5/.pnpm/axios@0.27.2/node_modules/axios/lib/adapters/http.js:262:25)
    at new Promise (<anonymous>)
    at httpAdapter (/root/.local/share/pnpm/global/5/.pnpm/axios@0.27.2/node_modules/axios/lib/adapters/http.js:49:10)
    at dispatchRequest (/root/.local/share/pnpm/global/5/.pnpm/axios@0.27.2/node_modules/axios/lib/core/dispatchRequest.js:58:10) {
  code: 'ERR_UNESCAPED_CHARACTERS'
}
获取关注贴吧失败：TypeError: Cannot read properties of undefined (reading 'toString')
成功签到0个, 失败0个, 过滤失效贴吧0个
push+发送一对一通知消息完成。

**Comment by sudojia** [comment]
根据你关注的贴吧来看，根本不需要转义，也不会发生转义问题，可能是运行环境问题吧，可以清除下 Cache，或者重装下青龙试试？目前我也不清楚，再者你可以单独把贴吧放在 GitHub 上运行
