### ISSUE TITLE
司机社签到失效

### ISSUE THREAD

**Issue by 2450519347** [sudojia/AutoTaskScript#29]
运行会报错
![Screenshot_2024-06-28-17-44-08-253_mark via](https://github.com/sudojia/scripts/assets/152893623/e0e6b4e6-3b9f-4ca1-9cb1-f5691f47f977)

**Comment by sudojia** [comment]
问题在于司机社应该是屏蔽了 GitHub Actions

**Comment by sudojia** [comment]
已测试，司机社已屏蔽 GitHub Actions

![image](https://github.com/sudojia/scripts/assets/86390796/09d4d3ba-d71f-4b2f-bcf1-0988a3382648)
