### ISSUE TITLE
青龙面板司机社签到失败

### ISSUE THREAD

**Issue by 2450519347** [sudojia/AutoTaskScript#33]
在自己的vps上搭建的青龙面板上运行司机社脚本签到失败，一台甲骨文云的美国机器上失败，一台阿里云的香港机器也失败，在家里软路由上也失败，都是报同样的错误
![Screenshot_2024-06-30-04-09-42-328_mark via](https://github.com/sudojia/scripts/assets/152893623/14307f3b-124e-4678-8b90-0562666ce8c3)

**Comment by sudojia** [comment]
自己手动添加诊断工具 check_sijishe.sh，排查吧

**Comment by sudojia** [comment]
我估计你选择的司机社地址是海外的，海外的加了个人机验证

**Comment by 2450519347** [comment]
> 我估计你选择的司机社地址是海外的，海外的加了个人机验证



> 我估计你选择的司机社地址是海外的，海外的加了个人机验证

解决了，还真是地址问题

**Comment by sudojia** [comment]
> > 我估计你选择的司机社地址是海外的，海外的加了个人机验证
> 
> > 我估计你选择的司机社地址是海外的，海外的加了个人机验证
> 
> 解决了，还真是地址问题

okk
