### ISSUE TITLE
新鲜的V2EX_COOKIE提示过期

### ISSUE THREAD

**Issue by xuanvivo** [sudojia/AutoTaskScript#37]
有空请看看，哪里出问题了，感激！
<img width="288" alt="image" src="https://github.com/sudojia/scripts/assets/64387331/79b086e6-732b-428a-a64e-df6d48de7d4e">

**Comment by sudojia** [comment]
噢噢，我是拿登录indexOf的，结果有个【领取今日的**登录**奖励】... 精确一点的话，应该要拿登出做判断

**Comment by xuanvivo** [comment]
> 噢噢，我是拿登录indexOf的，结果有个【领取今日的**登录**奖励】... 精确一点的话，应该要拿登出做判断

明白了，请大佬有空的话修复一下谢谢

**Comment by sudojia** [comment]
> > 噢噢，我是拿登录indexOf的，结果有个【领取今日的**登录**奖励】... 精确一点的话，应该要拿登出做判断
> 
> 明白了，请大佬有空的话修复一下谢谢

已修复

**Comment by xuanvivo** [comment]
> > > 噢噢，我是拿登录indexOf的，结果有个【领取今日的**登录**奖励】... 精确一点的话，应该要拿登出做判断
> > 
> > 
> > 明白了，请大佬有空的话修复一下谢谢
> 
> 已修复

火花带闪电啊！
感谢！
