### ISSUE TITLE
稀土掘金BUG

### ISSUE THREAD

**Issue by starsink-d** [sudojia/AutoTaskScript#39]
BUG 提交

**脚本名称**：sudojia_juejin.js

**问题描述**：

在运行稀土掘金时，查看日志发生异常，错误日志如下：

*****第[1]个稀土掘金账号*****
开始做社区活跃任务...
时间稍长、请耐心等待
【发布一条沸点】任务已完成，跳过...
【评论一篇文章】任务已完成，跳过...
【评论一条沸点】任务已完成，跳过...
开始执行【点赞一篇文章】任务...
未获取到沸点id, 请重试...
未获取到文章id, 请重试...
未获取到文章id, 请重试...
未获取到沸点id, 请重试...

**运行环境**：

- **面板/工具**：青龙面板2.11.3
- 
**附加信息**：

![image](https://github.com/sudojia/scripts/assets/112603695/4029309f-3310-40da-90aa-28d1b4e2813b)

之前用一直没啥问题这两天出现的问题

**Comment by xuanvivo** [comment]
我也是

开始执行稀土掘金

*****第[1]个稀土掘金账号*****
开始做社区活跃任务...
时间稍长、请耐心等待
【发布一条沸点】任务已完成，跳过...
【评论一篇文章】任务已完成，跳过...
【评论一条沸点】任务已完成，跳过...
开始执行【点赞一篇文章】任务...
未获取到沸点id, 请重试...
未获取到沸点id, 请重试...
未获取到沸点id, 请重试...
未获取到沸点id, 请重试...
未获取到文章id, 请重试...
未获取到文章id, 请重试...
未获取到文章id, 请重试...
未获取到文章id, 请重试...
未获取到文章id, 请重试...
未获取到文章id, 请重试...
未获取到文章id, 请重试...
未获取到沸点id, 请重试...
未获取到文章id, 请重试...
未获取到沸点id, 请重试...
未获取到沸点id, 请重试...
未获取到沸点id, 请重试...
未获取到文章id, 请重试...
未获取到文章id, 请重试...
未获取到文章id, 请重试...
未获取到文章id, 请重试...
未获取到文章id, 请重试...
未获取到沸点id, 请重试...
未获取到沸点id, 请重试...
未获取到沸点id, 请重试...
未获取到文章id, 请重试...
未获取到沸点id, 请重试...
未获取到文章id, 请重试...
未获取到文章id, 请重试...
未获取到文章id, 请重试...
未获取到沸点id, 请重试...
未获取到沸点id, 请重试...
未获取到沸点id, 请重试...
未获取到文章id, 请重试...
未获取到沸点id, 请重试...
未获取到文章id, 请重试...
未获取到沸点id, 请重试...
未获取到文章id, 请重试...
未获取到沸点id, 请重试...
未获取到沸点id, 请重试...
未获取到文章id, 请重试...
未获取到沸点id, 请重试...
未获取到沸点id, 请重试...
未获取到沸点id, 请重试...
未获取到文章id, 请重试...
未获取到文章id, 请重试...
未获取到沸点id, 请重试...
未获取到沸点id, 请重试...
未获取到沸点id, 请重试...
未获取到文章id, 请重试...
未获取到文章id, 请重试...
未获取到沸点id, 请重试...
未获取到文章id, 请重试...
未获取到文章id, 请重试...
未获取到沸点id, 请重试...
未获取到沸点id, 请重试...
未获取到文章id, 请重试...
未获取到文章id, 请重试...
未获取到沸点id, 请重试...
未获取到沸点id, 请重试...
未获取到沸点id, 请重试...
未获取到沸点id, 请重试...
未获取到文章id, 请重试...
未获取到文章id, 请重试...
未获取到沸点id, 请重试...
获取沸点id发生异常: TypeError: _0x786f90[_0xd1cb3d[_0x16d1]] is not iterable
未获取到沸点id, 请重试...
获取沸点id发生异常: TypeError: _0x786f90[_0xd1cb3d[_0x16d1]] is not iterable
未获取到沸点id, 请重试...
获取沸点id发生异常: TypeError: _0x786f90[_0xd1cb3d[_0x16d1]] is not iterable
未获取到沸点id, 请重试...
获取沸点id发生异常: TypeError: _0x786f90[_0xd1cb3d[_0x16d1]] is not iterable
未获取到沸点id, 请重试...
未获取到沸点id, 请重试...
未获取到沸点id, 请重试...
未获取到文章id, 请重试...
未获取到沸点id, 请重试...
未获取到文章id, 请重试...
未获取到文章id, 请重试...
未获取到沸点id, 请重试...
未获取到沸点id, 请重试...
未获取到沸点id, 请重试...
未获取到沸点id, 请重试...
未获取到文章id, 请重试...
未获取到文章id, 请重试...
未获取到文章id, 请重试...
未获取到文章id, 请重试...
未获取到文章id, 请重试...
未获取到沸点id, 请重试...
未获取到文章id, 请重试...
未获取到沸点id, 请重试...
未获取到文章id, 请重试...
未获取到沸点id, 请重试...
未获取到文章id, 请重试...
未获取到沸点id, 请重试...
未获取到沸点id, 请重试...
未获取到文章id, 请重试...
未获取到沸点id, 请重试...
未获取到沸点id, 请重试...
未获取到文章id, 请重试...
未获取到沸点id, 请重试...
未获取到沸点id, 请重试...
未获取到文章id, 请重试...
未获取到文章id, 请重试...
未获取到文章id, 请重试...
未获取到沸点id, 请重试...
未获取到沸点id, 请重试...
未获取到沸点id, 请重试...
未获取到文章id, 请重试...
未获取到沸点id, 请重试...
未获取到文章id, 请重试...
未获取到沸点id, 请重试...
未获取到沸点id, 请重试...
未获取到文章id, 请重试...
未获取到沸点id, 请重试...

**Comment by sudojia** [comment]
已修复，重新拉库！
