### ISSUE TITLE
掘金

### ISSUE THREAD

**Issue by Su0515** [sudojia/AutoTaskScript#40]
![image](https://github.com/sudojia/scripts/assets/124444534/d92de5ac-03d9-4cd2-9da1-762a5f8ef01c)

**Comment by Choicc** [comment]
这个问题新版已经修复了，但是新版本没走签到和抽奖
![image](https://github.com/sudojia/scripts/assets/24811393/5e08c7ed-6560-4c97-a8ed-046ddec86253)

**Comment by sudojia** [comment]
可能昨晚调试任务bug的时候注释掉了，晚点再看看

**Comment by sudojia** [comment]
重新拉库吧
