### ISSUE TITLE
霸王别姬可以多账号吗。用哪个分割符

### ISSUE THREAD

**Issue by runishiwo** [sudojia/AutoTaskScript#42]
## 功能请求

> 请先查看：[Issues 说明](https://github.com/sudojia/scripts/tree/script?tab=readme-ov-file#issues-%E8%AF%B4%E6%98%8E)

**网站 / 小程序**：https://xxxx.com / 某某某小程序

**入口**：登录之后右上角签到 / 某某某小程序 -> 我的 -> 签到

**奖励**：每日签到获得积分，积分可以兑换实物

**附加信息**：

- 上传截图
- 任何有助于的其他信息
- 不知名的最好附上官网链接，免得找半天

**Comment by sudojia** [comment]
&
