### ISSUE TITLE
快乐星球运行问题-多账户

### ISSUE THREAD

**Issue by wq-h** [sudojia/AutoTaskScript#43]
## BUG 提交

> 请先查看：[Issues 说明](https://github.com/sudojia/scripts/tree/script?tab=readme-ov-file#issues-%E8%AF%B4%E6%98%8E)

**脚本名称**：sudojia_joyPlanet.js

**问题描述**：

在青龙面板中添加两个JOY_PLANET_TOKEN token变量，运行脚本是只生效一个，第二个提示过期

```shell
*****第[2]个统一快乐星球账号*****
检测Token接口请求失败： TypeError: Cannot read properties of null (reading 'loginStatus')
    at lIl11Ill (/ql/data/scripts/sudojia_scripts_script/sudojia_joyPlanet.js:13:43130)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /ql/data/scripts/sudojia_scripts_script/sudojia_joyPlanet.js:13:32332

Token已失效
```

**重现步骤**：

1. 拉取最新脚本
2. 已按照文档获取并配置了脚本对应的环境变量JOY_PLANET_TOKEN
3. 点击运行
4. ...

**运行环境**：

- **面板/工具**：青龙面板 版本：v2.17.0
- **Node.js 版本**：v18.18.2

**附加信息**：

<img width="826" alt="image" src="https://github.com/sudojia/scripts/assets/38638778/2e64e135-72ee-4c40-a9cd-d7de8de88ad8">

**检查清单**：

- [ * ] 我已经查看了项目的文档和现有的 Issues，确定这个问题尚未被报告。
- [ * ] 我已经按照问题描述提供了足够的信息。
- [ * ] 我已经提供了脚本配置和运行环境的详细信息。
- [ * ] 我已经确定我的运行环境能够访问脚本对应的网站。

**Comment by sudojia** [comment]
token是不是有效的，快乐星球我记得token时效挺短的

**Comment by wq-h** [comment]
是有效的，我禁用第一个token，第二个就可以正常运行
```*****第[1]个统一快乐星球账号*****
Token 验证成功
昵称：南栀倾寒
开始签到...
请勿重复签到
本月签到1天，已连续签到1天
当前积分：105```

**Comment by sudojia** [comment]
重新拉库吧

**Comment by wq-h** [comment]
已解决
