### ISSUE TITLE
所有女生小程序找不到Authorization

### ISSUE THREAD

**Issue by Reverccb** [sudojia/AutoTaskScript#45]
## BUG 提交

> 请先查看：[Issues 说明](https://github.com/sudojia/scripts/tree/script?tab=readme-ov-file#issues-%E8%AF%B4%E6%98%8E)

**脚本名称**：sudojia_allGirls.js

**问题描述**：

抓包后，搜不到： Host: 7.wawo.cc 以及请求头 authorization 的值，搜 bearer也搜不到，其他脚本均正常

**重现步骤**：

**运行环境**：

- **面板/工具**：青龙面板
- **Node.js 版本**：青龙 2.16.5
- **服务器是否能正常访问脚本对应的网站**：我已通过 `ping tieba.baidu.com` 和 `curl -I tieba.baidu.com` 来确保能够正常访问该网站

**附加信息**：

- 上传截图
- 任何有助于理解问题的其他信息

**检查清单**：

> - [x] <- 这是打勾 demo，不会 markdown 就复制过去

- [1 ] 我已经查看了项目的文档和现有的 Issues，确定这个问题尚未被报告。
- [1 ] 我已经按照问题描述提供了足够的信息。
- [1 ] 我已经提供了脚本配置和运行环境的详细信息。
- [1 ] 我已经确定我的运行环境能够访问脚本对应的网站。

**Comment by sudojia** [comment]
那就不知道你了

![1720754703684](https://github.com/user-attachments/assets/de9f50c4-bf7e-4c97-9f95-80fc0378e742)
