### ISSUE TITLE
司机社签到失败

### ISSUE THREAD

**Issue by 2450519347** [sudojia/AutoTaskScript#46]
司机社自动签到显示成功签到但实际上并没有签到，已经换过签到地址以及服务器均是一样的错误，日志说已经签过到但是去网站查看没有签上。我怀疑是司机社给每个网站都加上了验证
![Screenshot_2024-07-12-04-45-44-769_mark via](https://github.com/sudojia/scripts/assets/152893623/b4fefdd5-b9ff-49bd-b89c-c1760471a136)

**Comment by sudojia** [comment]
这个得要没人的时候再看看

**Comment by sudojia** [comment]
我这里看了没什么问题

![image](https://github.com/user-attachments/assets/6d458ec3-7ff5-445d-ac90-c7e0ac8dea27)

![image](https://github.com/user-attachments/assets/7f320d89-e69c-45f2-bd92-6a9068dabbc5)

你这个应该是签到的时候，要么高峰期，要么司机社服务器不稳定，所以你这个获取到的都是 undefined，你可以修改下 cron，我默认的是 0 点

**Comment by sudojia** [comment]
针对你这个，目前加了个获取到 undefined 的话就尝试重新签到

**Comment by sudojia** [comment]
只是有个问题，在签到后，如果再次运行，它会获取不到，从而一直重新调用签到，设置一天一次即可

**Comment by 2450519347** [comment]
好的好的，我换了个时间试他又可以了，应该是司机社服务器的问题

**Comment by sudojia** [comment]
好的好的，快分享几个磁链🥳

**Comment by 2450519347** [comment]
> 针对你这个，目前加了个获取到 undefined 的话就尝试重新签到

把这个功能关了吧，加上这个之后好像我一直都签不上了

**Comment by sudojia** [comment]
> > 针对你这个，目前加了个获取到 undefined 的话就尝试重新签到
> 
> 把这个功能关了吧，加上这个之后好像我一直都签不上了

是域名换了，我刚看了你变量填的地址，访问了一下重定向了

![image](https://github.com/user-attachments/assets/947d8179-21bc-49c7-9936-26c0bc81d1b1)

你可以自己访问一下

**Comment by sudojia** [comment]
哥们发现问题了，是司机社加了个跳转验证

**Comment by sudojia** [comment]
https://t.me/c/1589534390/42

**Comment by 2450519347** [comment]
> 哥们发现问题了，是司机社加了个跳转验证

是的我之前打开网站他会有个跳转中然后再进去

**Comment by 2450519347** [comment]
> https://t.me/c/1589534390/42

加不了

**Comment by sudojia** [comment]
> > https://t.me/c/1589534390/42
> 
> 加不了

![image](https://github.com/user-attachments/assets/7c7aeae3-4050-428b-b680-7c6c53276b3c)

**Comment by sudojia** [comment]
改了一下，貌似还行把

![image](https://github.com/user-attachments/assets/c49417c6-0b64-4d4d-a9e1-84a244d90515)

**Comment by 2450519347** [comment]
> 改了一下，貌似还行把
> 
> ![image](https://private-user-images.githubusercontent.com/86390796/349356152-c49417c6-0b64-4d4d-a9e1-84a244d90515.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEyMzI3OTAsIm5iZiI6MTcyMTIzMjQ5MCwicGF0aCI6Ii84NjM5MDc5Ni8zNDkzNTYxNTItYzQ5NDE3YzYtMGI2NC00ZDRkLWE5ZTEtODRhMjQ0ZDkwNTE1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE3VDE2MDgxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU2YzYyNmE4MWJhOGM3YmM0NmJiZDJlMjI3NWE5YWQ1ZTIwZjNmYzEzNjM4YTRjZGU0ZTU0NWVkYzA5YmU5YjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jZWwRfoLEAI_JWzIz6sIo1c1p0W-mA-NamB7d-Hq3_I)

![Screenshot_2024-07-18-00-10-35-089_mark via](https://github.com/user-attachments/assets/9a1a5541-3bc8-43e0-9b4f-02df394475a4)
已经OK了，我看有别人提出说一对一通知失败，我刚刚也遇到了，提示什么requests timeout，然后去网上搜了下，到青龙容器里去执行一下npm cache clean --force再运行脚本通知就恢复正常了。
