### ISSUE TITLE
一对一推送失败

### ISSUE THREAD

**Issue by yinghuashuxiadiyishenqing** [sudojia/AutoTaskScript#47]
## BUG 提交

> 请先查看：[Issues 说明](https://github.com/sudojia/scripts/tree/script?tab=readme-ov-file#issues-%E8%AF%B4%E6%98%8E)

**脚本名称**：sudojia_kuro.js

**问题描述**：

一对一推送失败 更换了token还是不行

**运行环境**：
GitHub Actions

**Comment by sudojia** [comment]
未提供详细日志，也未提供使用哪个服务商

**Comment by yinghuashuxiadiyishenqing** [comment]
使用的GitHub Actions
服务器没问题 plus推送官方测试没问题

*****第[1]个库街区账号*****
开始社区签到...
社区签到失败：请勿重复签到
开始鸣潮每日签到...
鸣潮签到失败：请勿重复签到
检测到战双有角色，开始战双每日签到...
战双签到失败：请勿重复签到
push+发送一对一通知消息失败！！
Timeout awaiting 'request' for 15000ms
🔔库街区, 结束! 🕛 47.1[53](https://github.com/yinghuashuxiadiyishenqing/scripts/actions/runs/9901636856/job/27358028107#step:6:54) 秒
0s
Run Mattraks/delete-workflow-runs@main
  
💬 found total of 3 workflow run(s)
Error: Could not delete the workflow run
