### ISSUE TITLE
库洛签到没问题，但是推送失败，尝试5次后推送又成功，但是有错误

### ISSUE THREAD

**Issue by yinghuashuxiadiyishenqing** [sudojia/AutoTaskScript#48]
## BUG 提交

> 请先查看：[Issues 说明](https://github.com/sudojia/scripts/tree/script?tab=readme-ov-file#issues-%E8%AF%B4%E6%98%8E)

**脚本名称**：sudojia_kuro.js

**问题描述**：

库洛签到没问题，但是推送失败，尝试5次后推送又成功，但是有错误，日志如下：

##[debug]Evaluating condition for step: 'Delete Workflow Runs'
##[debug]Evaluating: success()
##[debug]Evaluating success:
##[debug]=> true
##[debug]Result: true
##[debug]Starting: Delete Workflow Runs
##[debug]Loading inputs
##[debug]Evaluating: github.token
##[debug]Evaluating Index:
##[debug]..Evaluating github:
##[debug]..=> Object
##[debug]..Evaluating String:
##[debug]..=> 'token'
##[debug]=> '***'
##[debug]Result: '***'
##[debug]Evaluating: github.repository
##[debug]Evaluating Index:
##[debug]..Evaluating github:
##[debug]..=> Object
##[debug]..Evaluating String:
##[debug]..=> 'repository'
##[debug]=> 'yinghuashuxiadiyishenqing/scripts'
##[debug]Result: 'yinghuashuxiadiyishenqing/scripts'
##[debug]Loading env
Run Mattraks/delete-workflow-runs@main
  
##[debug]  Added to del list 'kuro' workflow run 9901636856
##[debug]  Added to del list 'kuro' workflow run 9884696053
##[debug]  Added to del list 'kuro' workflow run 98673818[2](https://github.com/yinghuashuxiadiyishenqing/scripts/actions/runs/9901636856/job/27358155044#step:7:2)0
💬 found total of 3 workflow run(s)
##[debug]Deleting 'kuro' workflow run 99016[3](https://github.com/yinghuashuxiadiyishenqing/scripts/actions/runs/9901636856/job/27358155044#step:7:3)6856
Error: Could not delete the workflow run
##[debug]Node Action run completed with exit code 1
##[debug]Finishing: Delete Workflow Runs

**运行环境**：GitHub Actions

- **面板/工具**：GitHub Actions
![QQ_1720763841163](https://github.com/user-attachments/assets/791c51ed-f330-434a-8845-db3abfc42c4c)

**Comment by sudojia** [comment]
![image](https://github.com/user-attachments/assets/f941cd39-4ed3-4ec5-9cb9-24cde2297465)

你这不是能推送，主要GitHub Actions是国外，推送肯定有延迟，报错那个是删除Actions工作流，不影响，要么注释要么删掉

![image](https://github.com/user-attachments/assets/8b8ed5b9-b8cb-4e27-bc20-45f96f9d598c)
