### ISSUE TITLE
签到失败

### ISSUE THREAD

**Issue by liyw0205** [sudojia/AutoTaskScript#5]
![Screenshot_2022-05-15-09-59-21-11_40deb401b9ffe8e1df2f1cc5ba480b12](https://user-images.githubusercontent.com/86676694/168454006-3feba942-3d4a-4ff2-b482-95fc456ce274.jpg)

**Comment by sudojia** [comment]
葫芦侠在请求里加了个签名参数，暂时无解，现已移除hlx script
