### ISSUE TITLE
麻烦大佬看看，TypeError: Cannot read properties of undefined (reading 'country') 

### ISSUE THREAD

**Issue by jjj2025** [sudojia/AutoTaskScript#50]
## 开始执行... 2024-07-16 10:54:41

                  _         _  _        
  ___  _   _   __| |  ___  (_)(_)  __ _ 
 / __|| | | | / _` | / _ \ | || | / _` |
 \__ \| |_| || (_| || (_) || || || (_| |
 |___/ \__,_| \__,_| \___/_/ ||_| \__,_|
                         |__/           

----------------------------------------------------------
| 🌟 重要提示：                                          |
| 🍕 本脚本免费使用，遵循 GPLv3 许可证。                   |
| 🚫 脚本仅供学习交流，禁止用于商业用途！                   |
| 🛑 如果您是通过购买的方式获得本脚本，请立即停止使用！      |
| 🔍 并联系您的销售者了解详情。                            |
| ❗️ 任何形式的销售都是非法的！                            |
----------------------------------------------------------
检查版本时发生异常：TypeError: Cannot read properties of undefined (reading 'country')

麻烦大佬看看这个报错，所有的脚本都报country错误，我环境是群晖  container manager部署的青龙，前天能运行，就是提示什么海外加速我忘了，昨天开始不能运行了，报country错误。然后我把群晖DNS改8.8.8.8或者202.96.128.86都不行。

**Comment by sudojia** [comment]
更新最新版本，utils 的

**Comment by jjj2025** [comment]
感谢🙏

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年07月16日 11:53 |
| 收件人 | sudojia/scripts ***@***.***> |
| 抄送人 | jjj2025 ***@***.***>,
Author ***@***.***> |
| 主题 | Re: [sudojia/scripts] 麻烦大佬看看，TypeError: Cannot read properties of undefined (reading 'country') (Issue #50) |

更新最新版本，utils 的
