### ISSUE TITLE
智能电视脚本问题

### ISSUE THREAD

**Issue by binscor** [sudojia/AutoTaskScript#51]
## BUG 提交

**脚本名称**：sudojia_znds.js

**问题描述**：

智能电视运行了时出现了这个错误

**重现步骤**：

这个脚本我运行了挺久了，这两天发现出现了错误，昨天更新了相关的环境变量信息也还是不对，不知道是我这边的问题还是大家都出现了

**运行环境**：

- **面板/工具**：青龙面板 

**附加信息**：

- 上传截图
![image](https://github.com/user-attachments/assets/6a36d007-7cad-4aab-a52c-1fc714fb6ac2)

**检查清单**：

- [x] 我已经查看了项目的文档和现有的 Issues，确定这个问题尚未被报告。
- [x] 我已经按照问题描述提供了足够的信息。
- [x] 我已经提供了脚本配置和运行环境的详细信息。
- [x] 我已经确定我的运行环境能够访问脚本对应的网站。

**Comment by sudojia** [comment]
已修复，重新拉取新版本
