### ISSUE TITLE
掘金运行第一个任务就卡住不执行了

### ISSUE THREAD

**Issue by Choicc** [sudojia/AutoTaskScript#53]
## BUG 提交

> 请先查看：[Issues 说明](https://github.com/sudojia/scripts/tree/script?tab=readme-ov-file#issues-%E8%AF%B4%E6%98%8E)

**脚本名称**：sudojia_juejin.js

**问题描述**：

在运行执行到第一个任务时就卡住不动了：
![image](https://github.com/user-attachments/assets/a620f632-25c1-457a-94e4-b02b0330b824)

**重现步骤**：

1. 拉取最新脚本
2. 已按照文档获取并配置了脚本对应的环境变量 
3. 点击运行
4. ...

**运行环境**：

- **面板/工具**：青龙面板
- **服务器是否能正常访问脚本对应的网站**：我已通过 `ping juejin.cn`  来确保能够正常访问该网站

**检查清单**：

- [ ✅] 我已经查看了项目的文档和现有的 Issues，确定这个问题尚未被报告。
- [ ✅] 我已经按照问题描述提供了足够的信息。
- [ ✅] 我已经提供了脚本配置和运行环境的详细信息。
- [ ✅] 我已经确定我的运行环境能够访问脚本对应的网站。

**Comment by sudojia** [comment]
看不出问题，重新运行下，慢慢等着，看下最后有什么错误

**Comment by Choicc** [comment]
> 看不出问题，重新运行下，慢慢等着，看下最后有什么错误

之前的版本运行几个小时候就一直这样只是卡住，最新1.4.3版本出现以下报错
```
开始执行【发布一条沸点】任务...
任务列表发生异常: TypeError: Iilliil[llII[ii1i111I]] is not iterable
社区活跃任务已完成
共耗时：4分53秒
等待五秒左右...
```

**Comment by sudojia** [comment]
应该问题不大

**Comment by jjj2025** [comment]
我也有同样问题，发布一条沸点就卡在那了

**Comment by sudojia** [comment]
明天再看吧，没有号测试了

**Comment by jjj2025** [comment]
感谢大佬🙏

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年07月22日 16:19 |
| 收件人 | sudojia/scripts ***@***.***> |
| 抄送人 | jjj2025 ***@***.***>,
Comment ***@***.***> |
| 主题 | Re: [sudojia/scripts] 掘金运行第一个任务就卡住不执行了 (Issue #53) |

明天再看吧，没有号测试了

**Comment by Choicc** [comment]
![image](https://github.com/user-attachments/assets/5b42ed49-6b4a-4a17-a936-2df60d28ba11)
问题再次出现，已运行半个多小时了

**Comment by jjj2025** [comment]
问题一直都有，我感觉大部分人都有这问题，只不过有些人很久都不看一次脚本，压根不知道有报错

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年07月31日 09:00 |
| 收件人 | sudojia/scripts ***@***.***> |
| 抄送人 | jjj2025 ***@***.***>,
Comment ***@***.***> |
| 主题 | Re: [sudojia/scripts] 掘金运行第一个任务就卡住不执行了 (Issue #53) |

image.png (view on web)
问题再次出现，已运行半个多小时了
