### ISSUE TITLE
能否增加欣都龙城签到脚本，感谢！

### ISSUE THREAD

**Issue by sevenday** [sudojia/AutoTaskScript#54]
## 功能请求

> 请先查看：[Issues 说明](https://github.com/sudojia/scripts/tree/script?tab=readme-ov-file#issues-%E8%AF%B4%E6%98%8E)

**小程序**： 欣都龙城VCpark小程序

**入口**： 欣都龙城VCpark小程序 -> 签到

**奖励**：每日签到获得积分，积分可以兑换实物、兑换停车票等。

**附加信息**：

- 上传截图
![1](https://github.com/user-attachments/assets/bb7357c5-bfaf-4ee0-8310-98b2785a88ab)
![2](https://github.com/user-attachments/assets/9ce2f9d8-b9f0-4cf0-96bb-41f7deb91c50)
![3](https://github.com/user-attachments/assets/0f42878b-ac82-456d-a29e-df88a6a5858b)
- 任何有助于的其他信息
- 不知名的最好附上官网链接，免得找半天

**Comment by sudojia** [comment]
好了，https://github.com/sudojia/scripts/blob/script/sudojia_mallcoo.js 为了你，我下好的 GTA5 都还没开始玩

**Comment by sevenday** [comment]
> 好了，https://github.com/sudojia/scripts/blob/script/sudojia_mallcoo.js 为了你，我下好的 GTA5 都还没开始玩

可以用了，万分感谢大佬！
