### ISSUE TITLE
求增加【华住会】【东呈会】【长安汽车】APP签到，为感！

### ISSUE THREAD

**Issue by bandengzex** [sudojia/AutoTaskScript#56]
## 功能请求

> 请先查看：[Issues 说明](https://github.com/sudojia/scripts/tree/script?tab=readme-ov-file#issues-%E8%AF%B4%E6%98%8E)

**网站 / 小程序**：小程序【华住会】

**入口**：登录之后右上角签到 -正中心签到按钮

**奖励**：每日签到获得积分，积分可以抵扣房费，每100积分抵1元。一天签到1、3、5递增，5封顶，每周额外送50，也就是一个月签到得3~4元房费抵扣

**附加信息**：
APP【华住会】也可以抓到，他APP好像走的是网页协议，更新以前抓到过，后来更新失效了。

## 功能请求

> 请先查看：[Issues 说明](https://github.com/sudojia/scripts/tree/script?tab=readme-ov-file#issues-%E8%AF%B4%E6%98%8E)

**网站 / 小程序**：小程序【东呈酒店】

**入口**：登录之后首页中间-【签到/任务】按钮

**奖励**：也是每日签到积分可以抵扣房费，积分比华住会多。

**附加信息**：
无
## 功能请求

> 请先查看：[Issues 说明](https://github.com/sudojia/scripts/tree/script?tab=readme-ov-file#issues-%E8%AF%B4%E6%98%8E)

**网站 / 小程序**：APP【长安汽车】

**入口**：登录之后-【我】页面-右上角【签到】-进入后【签到】按钮

**奖励**：一天签到1、3、5递增，5封顶。可以在商城换各种会员，包括腾讯视频、优酷、芒果、爱奇艺等等

**附加信息**：
APP【长安汽车】【引力域】都是长安汽车的app，积分共同统计，但是签到是分开的，也就是两个app都能单独签到。
没有车也可以签到。

**Comment by sudojia** [comment]
长安汽车的，奥迪的，关于这类的，我模拟器都是打不开，所以抓不到包，其它的有时间再看看

![image](https://github.com/user-attachments/assets/449a586e-d1ba-4aa0-856d-548cfbc8087a)

**Comment by bandengzex** [comment]
> 长安汽车的，奥迪的，关于这类的，我模拟器都是打不开，所以抓不到包，其它的有时间再看看
> 
> ![image](https://private-user-images.githubusercontent.com/86390796/351534912-449a586e-d1ba-4aa0-856d-548cfbc8087a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE3OTg0NjAsIm5iZiI6MTcyMTc5ODE2MCwicGF0aCI6Ii84NjM5MDc5Ni8zNTE1MzQ5MTItNDQ5YTU4NmUtZDFiYS00YWEwLTg1NmQtNTQ4Y2ZiYzgwODdhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI0VDA1MTYwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM2ZmZiNzgxZjIzY2Y0YjZjMmI5NWJkZDZjMTZkNWY4ZGRiNzM2NmJhOTQ0NWQ3ZWQ4YjI2NWU5MzA5MzhmNmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.L_USZ4CE28drdpWMqZjUnYz7T30fceLJcvh9DH8KAlI)

对，而且在root未隐藏完全的手机上也不能正常运行。
