### ISSUE TITLE
稀土掘金运行任务报错，Error: getaddrinfo ENOTFOUND api.vvhan.com

### ISSUE THREAD

**Issue by jjj2025** [sudojia/AutoTaskScript#57]
开始执行稀土掘金

已随机分配 User-Agent

Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.99 Safari/537.36

*****第[1]个稀土掘金账号*****
开始做社区活跃任务...
时间稍长、请耐心等待
开始执行【发布一条沸点】任务...
任务列表发生异常: Error: getaddrinfo ENOTFOUND api.vvhan.com

已尝试更换DNS为1.1.1.1或者8.8.8.8都不行

**Comment by jjj2025** [comment]
开始执行稀土掘金

已随机分配 User-Agent

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36

*****第[1]个稀土掘金账号*****
开始做社区活跃任务...
时间稍长、请耐心等待
开始执行【发布一条沸点】任务...
任务列表发生异常: TypeError: Iilliil[llII[ii1i111I]] is not iterable


尝试第二次进行，发现新的报错

**Comment by starsink-d** [comment]
_         _  _        
  ___  _   _   __| |  ___  (_)(_)  __ _ 
 / __|| | | | / _` | / _ \ | || | / _` |
 \__ \| |_| || (_| || (_) || || || (_| |
 |___/ \__,_| \__,_| \___/_/ ||_| \__,_|
                         |__/           

----------------------------------------------------------
| 🌟 重要提示：                                          |
| 🍕 本脚本免费使用，遵循 GPLv3 许可证。                   |
| 🚫 脚本仅供学习交流，禁止用于商业用途！                   |
| 🛑 如果您是通过购买的方式获得本脚本，请立即停止使用！      |
| 🔍 并联系您的销售者了解详情。                            |
| ❗️ 任何形式的销售都是非法的！                            |
----------------------------------------------------------

使用本地缓存的 IP 地址信息

检测到服务器位于中国，将使用中国加速源检测版本

【脚本作者】sudojia
【脚本地址】https://github.com/sudojia/scripts
【当前版本】v1.4.3
【最新版本】v1.4.3
【最近更新】2024-07-22
【更新内容】更换文案 Api 接口，原先那个太骚了！

开始执行稀土掘金

已随机分配 User-Agent

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36

*****第[1]个稀土掘金账号*****
开始做社区活跃任务...
时间稍长、请耐心等待
开始执行【发布一条沸点】任务...
任务列表发生异常: AxiosError: Request failed with status code 504
社区活跃任务已完成
共耗时：0分37秒
等待五秒左右...
开始做每日签到任务...
签到成功，获得 700 矿石
开始执行十连抽...
检测到未配置十连抽环境变量，取消十连抽...
如需执行十连抽请配置环境变量【ENABLE_TEN_DRAW】为 true

server酱发送通知消息成功🎉

**Comment by starsink-d** [comment]
任务列表异常

**Comment by sudojia** [comment]
你们这都是网络有问题

https://baike.baidu.com/item/504%E9%94%99%E8%AF%AF/632323

Error: getaddrinfo ENOTFOUND api.vvhan.com 也是你连接不到  api.vvhan.com 这个 api，只能自行检查下网络了，若实在不行，只能用 GitHub Actions 单独跑这个来代替

**Comment by jjj2025** [comment]
我自己用电信宽带，换移动宽带也不行，更新之前是能运行的，更新后只能另想办法了
