### ISSUE TITLE
求增加【TILTA影像城】微信小程序每日签到和任务，感谢！

### ISSUE THREAD

**Issue by CheZhangLEO** [sudojia/AutoTaskScript#60]
功能请求
小程序：TILTA影像城
入口：登录之后我的-右上角签到
奖励：每日签到和任务完成获得铁币，积铁币可以兑换摄影配件实物
感谢大佬

**Comment by sudojia** [comment]
![image](https://github.com/user-attachments/assets/48a25995-6214-4231-953d-550cb69f9127)

好了，喜欢请支持
