### ISSUE TITLE
请求增加小程序签到----爷爷不泡茶

### ISSUE THREAD

**Issue by Ronaldo1109** [sudojia/AutoTaskScript#61]
## 功能请求

小程序：爷爷不泡茶小程序

入口：活动中心 -> 签到有礼 -> 签到

奖励：每日签到获得积分，连续签到可获奖励

附加信息：
        签到页面类同霸王茶姬，感觉可复用

**Comment by sudojia** [comment]
适用范围太小了，只有湖北才有门店，暂不考虑
