### ISSUE TITLE
稀土掘金每日签到失败

### ISSUE THREAD

**Issue by jjj2025** [sudojia/AutoTaskScript#63]
![image](https://github.com/user-attachments/assets/2ce83c26-215e-4345-8bad-32f4f8f384a0)

之前只是每日任务做不了，签到还是正常的，今天连签到也不行了，间隔运行过几次还是一样报错。

**Comment by sudojia** [comment]
https://t.me/IiiiOOiiiiOO/80

**Comment by klcb2010** [comment]
被封号了  
......
