### ISSUE TITLE
掘金脚本签到报错

### ISSUE THREAD

**Issue by Heylzh** [sudojia/AutoTaskScript#64]
## BUG 提交

**脚本名称**：sudojia_juejin.js

**问题描述**：

在运行掘金签到时，查看日志发生异常，错误日志如下：

```shell
签到发生异常: TypeError: Cannot read properties of undefined (reading 'incr_point')
```

**重现步骤**：

1. 拉取最新脚本
2. 已按照文档获取并配置了脚本对应的环境变量 JUEJIN_COOKIE
3. 点击运行
4. ...

**运行环境**：

- **面板/工具**：青龙面板

**附加信息**：

- 上传截图
![image](https://github.com/user-attachments/assets/9eae6de9-50da-418e-8e13-8f6f1cac9ae6)

**检查清单**：

- [x] 我已经查看了项目的文档和现有的 Issues，确定这个问题尚未被报告。
- [x] 我已经按照问题描述提供了足够的信息。
- [x] 我已经提供了脚本配置和运行环境的详细信息。
- [x] 我已经确定我的运行环境能够访问脚本对应的网站。

**Comment by sudojia** [comment]
https://t.me/IiiiOOiiiiOO/80

**Comment by sudojia** [comment]
应该是接口全部都换了，我也懒得维护了
