### ISSUE TITLE
功能请求

### ISSUE THREAD

**Issue by leesin321** [sudojia/AutoTaskScript#65]
##功能请求

**微信小程序**：南方航空

**入口**：南方航空小程序 -> 我 -> 签到

**奖励**：每日签到获得里程，里程可以兑换实物/机票

**附加信息**：

- 上传截图
![534E3FB9-CAB4-4DF6-9346-F8604C999E31](https://github.com/user-attachments/assets/5dd2c079-8b5d-40b5-b352-27b95feeab84)
![DFD016C9-5F6F-4187-94DD-189106E5EFB7](https://github.com/user-attachments/assets/3b34030b-cafd-40b3-acbe-1a986ae4ff2c)

**Comment by sudojia** [comment]
https://github.com/sudojia/scripts/blob/script/sudojia_nfhk.js
