### ISSUE TITLE
怎么投稿？有QQ吗？

### ISSUE THREAD

**Issue by huagemeinv** [sudojia/AutoTaskScript#68]
## 功能请求

> 请先查看：[Issues 说明](https://github.com/sudojia/scripts/tree/script?tab=readme-ov-file#issues-%E8%AF%B4%E6%98%8E)

**网站 / 小程序**：https://xxxx.com / 某某某小程序

**入口**：登录之后右上角签到 / 某某某小程序 -> 我的 -> 签到

**奖励**：每日签到获得积分，积分可以兑换实物

**附加信息**：

- 上传截图
- 任何有助于的其他信息
- 不知名的最好附上官网链接，免得找半天

**Comment by sudojia** [comment]
可以在 issues 提，可以在 tg 提 [@TrustedAideBot](https://t.me/TrustedAideBot) 也可以在群里 [@v_script](https://t.me/v_script)

但是不一定会写

**Comment by huagemeinv** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
