### ISSUE TITLE
OP商城这个本，还可以下载钱包app，里面还有签到，种树等其他任务可做

### ISSUE THREAD

**Issue by QQ313691952** [sudojia/AutoTaskScript#69]
https://www.123pan.com/s/nYqZVv-kexDv
大佬安装看下

**Comment by sudojia** [comment]
模拟器登录不了

**Comment by QQ313691952** [comment]
oppo和真我手机可以安装


小生活、兵慌马乱
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "sudojia/scripts"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年8月30日(星期五) 中午1:27
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [sudojia/scripts] OP商城这个本，还可以下载钱包app，里面还有签到，种树等其他任务可做 (Issue #69)





 
模拟器登录不了

**Comment by sudojia** [comment]
我手机抓不了包，我都是模拟器的

**Comment by QQ313691952** [comment]
https://reqable.com/zh-CN/
用这个抓包程序支持手机和桌面端
https://reqable.com/zh-CN/

小生活、兵慌马乱
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "sudojia/scripts"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年8月30日(星期五) 中午1:32
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [sudojia/scripts] OP商城这个本，还可以下载钱包app，里面还有签到，种树等其他任务可做 (Issue #69)





 
我手机抓不了包，我都是模拟器的

**Comment by sudojia** [comment]
没 root 可以不，安卓14

**Comment by QQ313691952** [comment]
没root不行，好像不支持安卓14，必须以下，我用的就是真我GT6，OPPO旗下的，账号信息和OPPO通用


小生活、兵慌马乱
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "sudojia/scripts"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年8月30日(星期五) 中午1:46
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [sudojia/scripts] OP商城这个本，还可以下载钱包app，里面还有签到，种树等其他任务可做 (Issue #69)





 
没 root 可以不，安卓14

**Comment by QQ313691952** [comment]
大佬居然还没root

**Comment by sudojia** [comment]
> 大佬居然还没root

我要是 root 了就不会用模拟器抓包了，以前玩机的时候天天搞机，刷第三方rom，现在都不折腾了，安安稳稳
