### ISSUE TITLE
功能需求打卡，嘉立创

### ISSUE THREAD

**Issue by fei12333** [sudojia/AutoTaskScript#70]
## 功能请求

> 请先查看：[Issues 说明](https://github.com/sudojia/scripts/tree/script?tab=readme-ov-file#issues-%E8%AF%B4%E6%98%8E)

**网站 / 小程序**：嘉立创 / 嘉立创下单助手小程序

**入口**：网页登录之后右下角我的-> 金豆 / 嘉立创下单助手小程序 -> 我的 -> 金豆 

**奖励**：每日签到获得积分，积分可以兑换实物

**附加信息**：

- 上传截图
- 任何有助于的其他信息
- 不知名的最好附上官网链接：（https://m.jlc.com/mapp），免得找半天

**Comment by sudojia** [comment]
居然是一些加工的东西

**Comment by sudojia** [comment]
有空写

**Comment by sudojia** [comment]
https://github.com/sudojia/scripts/blob/script/sudojia_jlc.js
