### ISSUE TITLE
OPPO商场签到失败

### ISSUE THREAD

**Issue by Z-TWO** [sudojia/AutoTaskScript#72]
## BUG 提交

> 请先查看：[Issues 说明](https://github.com/sudojia/scripts/tree/script?tab=readme-ov-file#issues-%E8%AF%B4%E6%98%8E)

**脚本名称**：sudojia_opposhop.js

**问题描述**：

无法签到：

```shell
签到失败 ->  { code: 5007, message: '活动已经结束', data: null, succeed: false }
```

**重现步骤**：

1. 执行脚本
2. 签到失败

**运行环境**：

- **面板/工具**：青龙面板 or GitHub Actions

**附加信息**：

- 上传截图
![image](https://github.com/user-attachments/assets/e896b283-df4f-482f-97b3-c1c30f53b81b)

**检查清单**：

- [x] 我已经查看了项目的文档和现有的 Issues，确定这个问题尚未被报告。
- [x] 我已经按照问题描述提供了足够的信息。
- [x] 我已经提供了脚本配置和运行环境的详细信息。
- [x] 我已经确定我的运行环境能够访问脚本对应的网站。

**Comment by sudojia** [comment]
更新吧，每个月都换活动ID的
