### ISSUE TITLE
WxPusher签到消息推送接口

### ISSUE THREAD

**Issue by Z-TWO** [sudojia/AutoTaskScript#73]
## 功能请求

**功能**：支持WxPusher消息推送的接口, 麻烦在提供一下消息推送的使用文档，编译后的代码无法查看如何使用

**Comment by Z-TWO** [comment]
大佬如果写文档麻烦，可以分享源码我来帮忙写，抱拳 @

**Comment by sudojia** [comment]
写多了容易写吐，源码在这 https://github.com/sudojia/scripts-docs 目录结构不清楚的可以问我

**Comment by sudojia** [comment]
在 PushPlus 7月份说要实名的时候，我就写了 WxPusher 了，变量名是 WXPUSHER_TOKEN、WXPUSHER_UID

就是文档没有写...

**Comment by sudojia** [comment]
https://rh-docs.netlify.app/docs/pushMsg/

**Comment by Z-TWO** [comment]
no problem，我去搞一下

**Comment by Z-TWO** [comment]
> https://rh-docs.netlify.app/docs/pushMsg/

这个是刚放上去了的吗？之前怎么好像没留意有

**Comment by Z-TWO** [comment]
![image](https://github.com/user-attachments/assets/19b9cd46-78a0-4bef-985b-caf7772e428f)
大佬看看这里是不是有问题，不管token和uid是啥，日志都显示成功

**Comment by Z-TWO** [comment]
![image](https://github.com/user-attachments/assets/2653b0d5-fa9e-41b1-ab7f-8d42f4d021de)
另外你只留了wxPush的token和uid变量，我看文档如果是使用我的token，我是需要创建一个主题（topic）对应的topicId，用户要订阅这个topic，才能收到消息的。所以你可以再加一个topiceId的变量，这样用户可以自己给自己发送消息

**Comment by Z-TWO** [comment]
> ![image](https://private-user-images.githubusercontent.com/52739659/363481814-2653b0d5-fa9e-41b1-ab7f-8d42f4d021de.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUxODUwNDksIm5iZiI6MTcyNTE4NDc0OSwicGF0aCI6Ii81MjczOTY1OS8zNjM0ODE4MTQtMjY1M2IwZDUtZmE5ZS00MWIxLWFiN2YtOGQ0MmY0ZDAyMWRlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTAxVDA5NTkwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNlZmRjZGJjYmQ3YjYwOGI0YWQ1M2M5ODVjNmZjYjg3OWJjZTAwNzYwMGU1YmU4OTI2YmYxYmZmMmY0ZDBkMWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qZzgtsMCpM2YDE647c7p1LQQM72vscsBZ7eYAqV9v4U) 另外你只留了wxPush的token和uid变量，我看文档如果是使用我的token，我是需要创建一个主题（topic）对应的topicId，用户要订阅这个topic，才能收到消息的。所以你可以再加一个topiceId的变量，这样用户可以自己给自己发送消息

或者是作者创建应用和topic，用户订阅，填写uid就可以收到消息

**Comment by Z-TWO** [comment]
![image](https://github.com/user-attachments/assets/4253b4b9-6fac-4451-b88d-e8f298e159c5)
还有这种成本比较低的，我个人觉得上面提到的第二种是修改成本最低的

**Comment by sudojia** [comment]
> ![image](https://private-user-images.githubusercontent.com/52739659/363481557-19b9cd46-78a0-4bef-985b-caf7772e428f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUxODcxNzMsIm5iZiI6MTcyNTE4Njg3MywicGF0aCI6Ii81MjczOTY1OS8zNjM0ODE1NTctMTliOWNkNDYtNzhhMC00YmVmLTk4NWItY2FmNzc3MmU0MjhmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTAxVDEwMzQzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZhYmI3YzcwYmUzYTg4YTJhNmMzZDczZTYzZTcxYTdhYmI0M2YzYjY5MDMwYjY4ZDU1NjI1NjkwMWY5N2ViNmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Fzyiq2zxXXTVQ55nezvyDzlkpvkH6pGannVWgsVaht8) 大佬看看这里是不是有问题，不管token和uid是啥，日志都显示成功

你这个看的是 pushPlus 的

**Comment by sudojia** [comment]
> ![image](https://private-user-images.githubusercontent.com/52739659/363481814-2653b0d5-fa9e-41b1-ab7f-8d42f4d021de.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUxODcxNzMsIm5iZiI6MTcyNTE4Njg3MywicGF0aCI6Ii81MjczOTY1OS8zNjM0ODE4MTQtMjY1M2IwZDUtZmE5ZS00MWIxLWFiN2YtOGQ0MmY0ZDAyMWRlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTAxVDEwMzQzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE0YmYzOWI4NzJhNzM2MGZlNGQyMzQwMWU2NDA0OWRmYTdiODg3YTAyZjQwMDAzMTlkMTMxN2FjNzcwNGZmYTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.z6Q1g-921aJvqO_TVAsu3bzXuDYb2IVs_iIcN6eL4Us) 另外你只留了wxPush的token和uid变量，我看文档如果是使用我的token，我是需要创建一个主题（topic）对应的topicId，用户要订阅这个topic，才能收到消息的。所以你可以再加一个topiceId的变量，这样用户可以自己给自己发送消息

创建主题没必要，那种是多个用户的了

UID 是单独的，一般 UID 就够了

> //发送目标的topicId，是一个数组！！！，也就是群发，`使用uids单发的时候， 可以不传。`

**Comment by sudojia** [comment]
你创建应用之后获取 appToken 之后，关注公众号再获取 UID 就正常可以用了

**Comment by Z-TWO** [comment]
原来要订阅应用，可以了，感谢大佬。
