### ISSUE TITLE
兴攀农场报错

### ISSUE THREAD

**Issue by Z-TWO** [sudojia/AutoTaskScript#74]
## BUG 提交

**脚本名称**：sudojia_xpfarm.js

**问题描述**：

在运行签到时，查看日志发生异常，错误日志如下：

```shell
检查版本时发生异常：Error: error:1C800064:Provider routines::bad decrypt
```

**重现步骤**：

1. 拉取最新脚本
2. 已按照文档获取并配置了脚本对应的环境变量 XPFARM_TOKEN
3. 点击运行

**附加信息**：

![image](https://github.com/user-attachments/assets/6b41447c-e75b-4879-99a3-91b0e01d95bb)

**检查清单**：

- [x] 我已经查看了项目的文档和现有的 Issues，确定这个问题尚未被报告。
- [x] 我已经按照问题描述提供了足够的信息。
- [x] 我已经提供了脚本配置和运行环境的详细信息。
- [x] 我已经确定我的运行环境能够访问脚本对应的网站。

**Comment by sudojia** [comment]
重新拉库重新拉库

**Comment by xoyo-tyu** [comment]
重新拉库也是一样的问题，环境问题头大的
