### ISSUE TITLE
脚本怎么都寄了

### ISSUE THREAD

**Issue by Z-TWO** [sudojia/AutoTaskScript#77]
## BUG 提交

**脚本名称**：ALL

**问题描述**：

检查版本时发生异常：Error: error:1C800064:Provider routines::bad decrypt

**附加信息**：

![image](https://github.com/user-attachments/assets/cd736ad0-d44d-4563-ab95-4e42fedf0463)

**Comment by sudojia** [comment]
emmm... 你没有定时自动更新脚本吗？这都过了好久了

![image](https://github.com/user-attachments/assets/61875128-bb21-480e-a4a2-73db25633f19)

**Comment by Z-TWO** [comment]
你这是tg的吗
