### ISSUE TITLE
功能请求

### ISSUE THREAD

**Issue by amudream** [sudojia/AutoTaskScript#78]
微信小程序：南方航空

入口：南方航空小程序 -> 首页 -> 每日抽免票
入口：#小程序://南方航空/R65EHZvOytzIQJA

奖励：抽奖获得机票，实物或者里程，里程可以兑换实物/机票，中奖率比较高

**Comment by sudojia** [comment]
南航的好像失效很快

**Comment by amudream** [comment]
![image](https://github.com/user-attachments/assets/019b5afb-ac19-4e8d-866c-ff76393d3b99) 果然漏了一天😭，大佬有空实现一下吧，三天也是好的🥹

**Comment by sudojia** [comment]
活动还有吗
