### ISSUE TITLE
运行成功但无法成功签到

### ISSUE THREAD

**Issue by sanqianyanyi** [sudojia/AutoTaskScript#8]
作者您好，我和您用的应该是一个机场，这边我运行成功签到了，tg机器人没有推送，也没有成功签到。
![QQ截图20220910131117](https://user-images.githubusercontent.com/71774177/189470147-19404b85-1c79-4dd7-99ed-65c9f8c5f199.png)

**Comment by sudojia** [comment]
首先你得点进去看看log，你这样我很难解决，有时候虽然是成功的绿色标志，但是log会显示出错，我刚刚也随便用了家机场测试了一下，没问题的

![image](https://user-images.githubusercontent.com/86390796/192421804-c511af47-43bc-46da-bff7-eee3768afb0c.png)

**Comment by sanqianyanyi** [comment]
> 你得先看看日志，你这样我却显示不出来，虽然是成功的结果标志，我刚刚也顺便用了家会的日志，测试了一下，
> 
> ![图片](https://user-images.githubusercontent.com/86390796/192421804-c511af47-43bc-46da-bff7-eee3768afb0c.png)

不好意思，我刚刚看了一下，发现好像是cf五秒盾的问题，导致请求没有正确访问
