### ISSUE TITLE
请求添加fnos论坛签到

### ISSUE THREAD

**Issue by runishiwo** [sudojia/AutoTaskScript#82]
## 功能请求

**网站：https://club.fnnas.com/plugin.php?id=zqlj_sign

**入口**：登录之后右上角签到

**奖励**：每日签到获得飞牛币，暂未发现能换什么东西

**附加信息**：

**Comment by sudojia** [comment]
https://github.com/sudojia/scripts/blob/script/sudojia_fnnas.js
