### ISSUE TITLE
飞牛这个有点小BUG

### ISSUE THREAD

**Issue by runishiwo** [sudojia/AutoTaskScript#83]
## BUG 提交

今天没有打卡，运行脚本提示已打卡，最近打卡日期也是昨天的

**脚本名称**：sudojia_fnnas.js

**问题描述**：

## 开始执行... 2024-09-21 00:09:01

                  _         _  _        
  ___  _   _   __| |  ___  (_)(_)  __ _ 
 / __|| | | | / _` | / _ \ | || | / _` |
 \__ \| |_| || (_| || (_) || || || (_| |
 |___/ \__,_| \__,_| \___/_/ ||_| \__,_|
                         |__/           

【脚本作者】sudojia
【脚本地址】https://github.com/sudojia/scripts
【TG-频道】https://t.me/IiiiOOiiiiOO
【TG-群组】https://t.me/v_script
【当前版本】v1.0.0
【最新版本】v1.0.0
【最近更新】2024-09-20
【更新内容】飞牛私有云每日打卡

开始执行飞牛私有云

已随机分配 User-Agent

Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.102 Safari/537.36

*****第[1]个飞牛私有云账号*****
FAZAA2A12(3415)
今日已打卡
最近打卡：2024-09-20 20:21:40
本月打卡：2天
连续打卡：2天
累计打卡：2天
累计奖励：18飞牛币
最近奖励：10飞牛币
当前打卡等级：无名新人
当前积分：0
当前牛值：0
当前飞牛币：33
当前登录天数：3

**Comment by sudojia** [comment]
判断错了，没注意看下面还有这么多今日已打卡

![image](https://github.com/user-attachments/assets/c4de31fa-2edc-488e-9752-72e0eeaf4324)
