### ISSUE TITLE
网易云音乐云贝签到

### ISSUE THREAD

**Issue by TeslaCybercab** [sudojia/AutoTaskScript#84]
## 功能请求

                           网易云音乐云贝签到

**网站 / 小程序**：https://xxxx.com / 某某某小程序

                            网易云音乐客户端

**入口**：登录之后右上角签到 / 某某某小程序 -> 我的 -> 签到

                    PC客户端 下拉箭头（手机版没下载不知道）

**奖励**：每日签到获得积分，积分可以兑换实物

                                可以兑换会员

**附加信息**：

- 上传截图
![image](https://github.com/user-attachments/assets/3ff6d779-67f2-4cac-b2e0-5d0875f0a27a)

**Comment by sudojia** [comment]
这个暂不考虑，可以使用开源项目 [SPlayer](https://github.com/imsyy/SPlayer)
