### ISSUE TITLE
可以加一个每天定时推送失效的token的任务吗

### ISSUE THREAD

**Issue by runishiwo** [sudojia/AutoTaskScript#85]
希望有一个脚本会每天定时推送失效token的任务的脚本

比如今天有以下任务token失效：
xxx
xxx
xxx
之类的。

**Comment by runishiwo** [comment]
或者每天定时检查下所有token的任务

**Comment by sudojia** [comment]
@runishiwo 这个上个礼拜就在开发了，写到一半了，还在整合

**Comment by sudojia** [comment]
https://t.me/IiiiOOiiiiOO/112
