### ISSUE TITLE
霸王茶姬社群签到

### ISSUE THREAD

**Issue by leave668** [sudojia/AutoTaskScript#92]
### 📲 服务平台

微信小程序

### 🧸 应用官网

霸王茶姬

### 🤔 活动入口

https://3ct.cc/qXZAc85A
10月签到得好礼 最高🉐买一赠一券 

### 🎁 奖励说明

10月连续签到得好礼 最高🉐买一赠一券 

### 🔗 附加信息

每个月有新的社群签到地址

**Comment by sudojia** [comment]
链接无效，入口也找半天

![image](https://github.com/user-attachments/assets/e8230424-779c-47df-bf6e-47dd8cb4fbe7)
