### ISSUE TITLE
嘉立创脚本今日更新后无法使用

### ISSUE THREAD

**Issue by fei12333** [sudojia/AutoTaskScript#93]
### 📜 脚本名称

sudojia_jlc.js（嘉立创）

### 🤔 问题描述

今天更新以后无法正常签到，有报错

### 🔄 重现过程

![image](https://github.com/user-attachments/assets/1efe3da5-6aed-472c-b226-7823e56a43b1)
已按照文档说明要求获取的 Cookie 格式

### 🌐 网络自检

是

### 🔗 附加信息

![image](https://github.com/user-attachments/assets/921c67c3-ba5f-4943-8571-a446a1b3f53b)更新以后就签到不了了

**Comment by sudojia** [comment]
更新青龙版本 > `2.17.x`

**Comment by fei12333** [comment]
我目前的版本是 2.17.9，但是就是会有上面提出的问题

**Comment by sudojia** [comment]
目录结构 [README](https://github.com/sudojia/AutoTaskScript?tab=readme-ov-file#%E9%A1%B9%E7%9B%AE%E6%9E%B6%E6%9E%84) 也有写，自行在脚本管理查看目录结构，
