### ISSUE TITLE
得物玩一玩

### ISSUE THREAD

**Issue by TeslaCybercab** [sudojia/AutoTaskScript#96]
### 📲 服务平台

客户端

### 🧸 应用官网

得物APP

### 🤔 活动入口

最下栏-探索-玩一玩里的游戏和签到

### 🎁 奖励说明

可以兑换商品以及折扣优惠卷

### 🔗 附加信息

![a5a4d0b6085ca0aafc77fed132cacc0f](https://github.com/user-attachments/assets/1f8973f2-5a50-4758-b6b2-c3b48baff1bf)

**Comment by sudojia** [comment]
暂时没这个打算，前面抓过看了，太多任务接口要写了，没时间写，而且外面也有脚本，自己找一找就好啦

![image](https://github.com/user-attachments/assets/e978a046-b917-40ce-92a0-57188409414f)
