### ISSUE TITLE
小程序 雀巢会员俱乐部

### ISSUE THREAD

**Issue by TeslaCybercab** [sudojia/AutoTaskScript#97]
### 📲 服务平台

微信小程序

### 🧸 应用官网

雀巢会员俱乐部

### 🤔 活动入口

右下角->我的 -> 赚巢币攻略(查看全部) -> 每日浏览官网

### 🎁 奖励说明

签到积分兑实物

### 🔗 附加信息

![c3b804e4a41c52c120f890703306595a](https://github.com/user-attachments/assets/07b0e197-8f71-4641-9d13-1c954615e209)

**Comment by sudojia** [comment]
下午写

**Comment by sudojia** [comment]
https://github.com/sudojia/AutoTaskScript/blob/script/src/wx_mini/sudojia_nestle.js
