### ISSUE TITLE
特步签到失效

### ISSUE THREAD

**Issue by TeslaCybercab** [sudojia/AutoTaskScript#98]
### 📜 脚本名称

特步

### 🤔 问题描述

无法签到

### 🔄 重现过程

抓包也找不到脚本所需得关键字

### 🌐 网络自检

是

### 🔗 附加信息

![39dff623f7f69ffed222d2d90083e9b3](https://github.com/user-attachments/assets/393dba07-7ad2-43be-aba5-340fe436533d)
![2024-10-15_10-45-57](https://github.com/user-attachments/assets/8bdd86a2-8892-41b9-b397-e8d330225510)

**Comment by sudojia** [comment]
已修复，查看脚本头部注释重新获取 `token`
